### ISSUE TITLE
Exception while setting garbage value to object with 'Double' field

### ISSUE THREAD

**Issue by look1n** [Commit451/ParcelCheck#3]
I've faced exception while running test with ParcelCheck. I have bean object with Double field 'creditCardFee' in my project. I did some debug of ParcelCheck sources and found code that generate dummy values to fill objects and it has this line of code:
`if(!Float.class.isAssignableFrom(clazz) && !Float.TYPE.isAssignableFrom(clazz) && !Double.class.isAssignableFrom(clazz) && !Double.TYPE.isAssignableFrom(clazz)) {`
So my question is should we split this condition to fill Float and Double separately?

P.S. Exception stack trace

> java.lang.IllegalArgumentException: field ...creditCardFee has type java.lang.Double, got java.lang.Float
> at java.lang.reflect.Field.set(Native Method)
> at com.commit451.parcelcheck.ObjectHelper.fillWithGarbage(ObjectHelper.java:50)
> at com.commit451.parcelcheck.ObjectHelper.getTestObject(ObjectHelper.java:130)
> at com.commit451.parcelcheck.ParcelCheckPackageTest.testParcels(ParcelCheckPackageTest.java:42)

**Comment by Jawnnypoo** [comment]
Ahh, I am able to reproduce this. Thanks for reporting. Lemme see what we can do

**Comment by Jawnnypoo** [comment]
This should be fixed with 1.0.2 Please let me know if it works for you

**Comment by look1n** [comment]
Fix works for me, thanks.
